# Generated by Django 4.2.3 on 2023-08-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_store_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
    ]
