# Generated by Django 4.2.3 on 2023-08-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
