# Generated by Django 4.2.3 on 2023-08-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_alter_listing_price_delete_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pictures',
            field=models.ManyToManyField(related_name='images', to='listing.image'),
        ),
    ]
