# Generated by Django 4.2.3 on 2023-08-01 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_alter_listing_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='pictures',
        ),
        migrations.AddField(
            model_name='image',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.listing'),
        ),
    ]
