# Generated by Django 4.2.4 on 2023-08-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_alter_image_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(choices=[('MEN', 'men'), ('FEMALE', 'female'), ('KIDS', 'kids'), ('UNISEX', 'unisex')], max_length=100, null=True),
        ),
    ]
