# Generated by Django 4.2.4 on 2023-08-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_cartiten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartiten',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
