# Generated by Django 4.2.4 on 2023-08-31 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0014_alter_cartiten_listing_alter_cartiten_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fav_item', to='listing.listing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
